# Generated by Django 3.2.20 on 2023-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_auto_20230829_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=6000)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('mobile_no', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('landmark', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
