# Generated by Django 3.2.20 on 2023-09-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_alter_orderupdate_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='o_id',
        ),
    ]
