# Generated by Django 3.2.20 on 2023-09-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_remove_orders_o_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(blank=True, default='UNPAID', max_length=20),
        ),
    ]
