# Generated by Django 3.2.21 on 2023-09-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_alter_orders_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
